version: "3"
services:
  node1:
    image: node1
    build:
      context: ./node1/
    networks:
      - tradermarynet
    volumes:
      - ./node1/daemons:/etc/frr/daemons
    cap_add:
      - NET_ADMIN
  node2:
    image: node2
    build:
      context: ./node2/
    networks:
      - tradermarynet
    volumes:
      - ./node2/daemons:/etc/frr/daemons
    cap_add:
      - NET_ADMIN
  node3:
    image: node3
    build:
      context: ./node3/
    networks:
      - tradermarynet
    volumes:
            - ./node3/daemons:/etc/frr/daemons
    cap_add:
      - NET_ADMIN
networks:
  tradermarynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.16.0.0/16
